# DevOps管理平台配置文件

# 应用配置
app:
  name: "作业管理平台"
  version: "0.1"
  environment: "production"  # development, production, test
  port: 8080

# 数据库配置
database:
  type: "mysql"  # sqlite, mysql
  # SQLite 配置
  sqlite:
    file: "devops.db"
  # MySQL 配置
  mysql:
    host: "192.168.200.182"
    port: 3306
    username: "devops"
    password: "123456"
    database: "devops"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"

# JWT配置
jwt:
  secret: "your-secret-key-change-in-production"
  expire_hours: 24

# 日志配置
logging:
  level: "info"
  to_file: true
  file_path: "log/"

# 定时任务配置
scheduler:
  enabled: true
  host_check_interval: "5m"
